### ISSUE TITLE
Workflow fails for forked PRs

### ISSUE THREAD

**Issue by doomlerd** [bradennapier/eslint-plus-action#38]
seems to result in the following error no matter what change I make to the workflow
```
##[error]TypeError: state.rulesSummaries.get is not a function
##[error]state.rulesSummaries.get is not a function
```

run link : https://github.com/doomlerd/pp/pull/5/checks?check_run_id=945708841
aside from the error, would it be possible to apply the workflow to PRs that are already open?

**Comment by bradennapier** [comment]
You could apply to PRs that are open by using the manual dispatch, it would require some hackery by taking in the branch to apply to as an option than using actions/checkout with that as the ref but no changes would be needed for the eslint action i believe.

As for the error you are getting, I think that is actually due to your eslint version.  Can you update it to at least `6.8.0`?

**Comment by doomlerd** [comment]
Hi,
I've updated ESLint to v6.8.0 but I'm still getting the same error
(https://github.com/doomlerd/pp/pull/6/checks?check_run_id=946607137)

**Comment by bradennapier** [comment]
Yeah I see the cause and have a fix ready but didn't have time to publish it yet.

**Comment by doomlerd** [comment]
Is there any workaround that I could make while you push a fix for it? our community depends on it.
