### ISSUE TITLE
Remote PR Currently Fails

### ISSUE THREAD

**Issue by bradennapier** [bradennapier/eslint-plus-action#6]
This is a known issue with how github actions works, have to investigate to see if there is a fix we can do:

```
# GITHUB_TOKEN in forked repositories is read-only
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }} 
```

The above can be used to skip in the meantime if its a remote PR so that the checks do not always fail

**Comment by bradennapier** [comment]
Note: https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token

**Comment by luisherranz** [comment]
We are also facing the same problem. May I ask why does the action need write permissions? Is it to delete the previous comment?

**Comment by bradennapier** [comment]
Creating checks, annotations, issues, deleting the previous issue so it doesn't spam are all write actions.  

The github token by default has read/write to the repo only and nothing else unless its a remote fork.  #11 goes over my plan to allow remote forks to work without breaking the security.

**Comment by luisherranz** [comment]
I don't know about checks and annotations but have you thought about editing the previous comment instead of deleting/adding a new one? That's what other actions do, like for example https://github.com/iam4x/now-deploy-preview-comment. I guess you don't need write access for that, as it belongs to the same GitHub user, although I'm not 100% sure.

**Comment by bradennapier** [comment]
You would need write access for editing.  The reason I am not editing is just because I had wanted it to update on the timeline, but edit may be a better path.

**Comment by luisherranz** [comment]
> My solution using the scheduled job will always run on the master branch so its secure in that sense and will have access to the secrets and such

That's a really interesting workaround. Can it access the artifacts of another branch or do you need an external service to store them?

**Comment by bradennapier** [comment]
Not when using github packages, they restrict them on the client but the api itself doesn’t restrict it so they can be accessed.

So the plan will be whenever it runs it will query artifacts for the repository, scan through them since the last run and run the updates and remove the artifacts once successful. 

I‘ve confirmed the solution now so should be ready soon.

**Comment by luisherranz** [comment]
> I've confirmed the solution now so should be ready soon.

That is awesome. To be honest, I've been searching for solutions to this problem since my early days using GH actions and never found anyone using/proposing a workaround, not even the official answers from the GH team. This approach seems like it could be that missing piece 👏

> Hoping to generalize the solution so other GitHub actions can take advantage.

Like a library that could be used to make a GH action "schedulable"?

**Comment by bradennapier** [comment]
BAM https://github.com/bradennapier/eslint-plus-action/pull/13/checks?check_run_id=843960041

**Comment by luisherranz** [comment]
Testing it out in https://github.com/frontity/frontity/pull/515. Everything seems great so far 👍
